bot/urls.py
from django.urls import path
from bot.views import *

app_name = 'bot'

urlpatterns = [
    path('', UpdateBot.as_view(), name='update'),
    path('send/<str:user_id>/', user_send_message, name='send_message'), #type:ignore
    path('send/<str:user_id>/pedido/<str:pedido_id>/', enviar_detalle_pedido, name='send_pedido'), #type:ignore
]

main/urls.py
from django.urls import path
from main.views import *

app_name = 'main'

urlpatterns = [
    path('', inicio_view, name='inicio'),
    path('bot-user-profile/<str:user_id>/', bot_user_profile, name='bot_user_profile'),
    path('bot-user-profile/<str:user_id>/send-message/', bot_user_profile, name='bot_user_message'),
    path('detalle-ahorro/', detalle_ahorro, name='detalle_ahorro'),
    path('search/', search_view, name='search'),
    path('users-list/', users_list_view, name='users_list'),
]

main/models.py
from django.db.models import *


class Settings(Model):

    nombre = CharField("Nombre", max_length=50)
    descripcion = CharField(
        "Descripcion", max_length=100, blank=True, null=True)
    valor = CharField("Valor", max_length=50)

    class Meta:
        verbose_name = "Settings"
        verbose_name_plural = "Settings"

    def __str__(self):
        return self.valor

class Monto(Model):

    monto = IntegerField()
    inserted_on = DateField(auto_now_add=True)

    class Meta:
        verbose_name = 'Monto'
        verbose_name_plural = 'Montos'

    def __str__(self):
        return str(self.monto)

main/views.py
import random
from datetime import date
from django.db.models import Sum
from django.shortcuts import render, get_object_or_404
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from productos.models import Categoria, Detalles
from bot.models import BotUser, Activity
from bot.forms import MessageForm
from comanda.models import Comanda
from main.models import Monto
from main.utils import get_today
from socios.models import Socio
from home.decorators import allowed_users


@staff_member_required
def bot_user_profile(request, user_id):
    context, template = {}, 'apps/bot/bot_user_profile.html'
    bot_user = BotUser.objects.get(user_id=user_id)
    form = MessageForm()
    if request.method == 'POST':
        form = MessageForm(request.POST or None)
    context = {
        'user': bot_user,
        'form': form
    }
    return render(request, template, context)

@staff_member_required
def detalle_ahorro(request):
    template = 'apps/main/detalle_ahorro.html'
    amounts_list = Monto.objects.all().order_by('-inserted_on')
    page = request.GET.get('page',  1)
    
    paginator = Paginator(amounts_list, 10)
    try:
        detalle = paginator.page(page)
    except PageNotAnInteger:
        detalle = paginator.page(1)
    except EmptyPage:
        detalle = paginator.page(paginator.num_pages)
    context = {
        'detalle' : detalle 
    }
    return render(request, template, context)


@staff_member_required
def users_list_view(request):
    template = 'apps/bot/users_list.html'
    context = {
        'users_list': BotUser.objects.all().order_by('-inserted_on')
    }

    return render(request, template, context)


@login_required
def inicio_view(request):
    context, template = {}, "apps/main/inicio.html"
    socios = Socio.objects.all()
    productos = Categoria.objects.all()
    detalles = Detalles.objects.all()
    users = BotUser.objects.all()
    # activities = Activity.objects.values('inserted_on__date').distinct().values('user_id').distinct()
    today = get_today()
    activities = Activity.objects.all().order_by('-inserted_on')[:25]
    comandas = Comanda.objects.filter(fecha=today).order_by('-pk')
    try:
        operador = request.user.groups.get(name='operadores')
    except:
        operador = None
    
    context = {
        'productos': productos,
        'detalles' : detalles,
        'users': users,
        'activities': activities,
        'comandas' : comandas,
        'operador' : operador,
        'socios' : socios,
        'latest' : socios.order_by('-persona__created_on')[:8],
        'hoy': today,
    }

    return render(request, template, context)

def get_amount(ok):
    while ok:
        amount = random.randint(1,28)
        ok = False if Monto.objects.filter(monto=amount, inserted_on__icontains=date.today().year).count() <= 13 else True
            
    return amount

# SEARCH_TYPE_MAPPING = {
#     'receta': Receta,
#     'recetas': Receta,
#     'socio': Socio,
#     'socios': Socio
# }

# @staff_member_required
# def search_view(request):
#     context, template = {}, 'apps/main/search/results-view.html'
#     query = request.GET.get('q')
#     search_type = request.GET.get('type')
#     Klass = SEARCH_TYPE_MAPPING[search_type] if search_type in SEARCH_TYPE_MAPPING else Socio
#     qs = Klass.objects.search(query=query)
#     context['objects'] = qs

#     if request.htmx:
#         context['objects'] = qs[:5]
#         template = 'apps/main/search/partials/results.html'
    
#     return render(request, template, context)

# @allowed_users(allowed_roles=['admin', 'operadores'])
def search_view(request):
    context, template = {}, 'apps/main/search/results-view.html'
    query = request.GET.get('q')
    qs = Socio.objects.search(query=query) #type: ignore
    context['objects'] = qs
    if request.htmx:
        context['objects'] = qs[:10]
        template = 'apps/main/search/partials/results.html'
    
    return render(request, template, context)

templates/apps/main/search/results-view.html
{% extends 'base.html' %}

{% block content-header %}
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
        <div class="col-sm-6">
            <h1 class="m-0 text-dark">Resultados</h1>
        </div><!-- /.col -->
        <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="{% url 'main:inicio' %}">Inicio</a></li>
            <li class="breadcrumb-item active">Resultados</li>
            </ol>
        </div><!-- /.col -->
        </div><!-- /.row -->
    </div>
</div>
{% endblock content-header %}

{% block main-content %}
<section class="content">
    <div class="container-fluid">
        {% include 'apps/main/search/partials/results.html' %}
    </div>
</section>

{% endblock main-content %}

templates/apps/main/search/search-form.html
<form action="{% url "main:search" %}" method="GET" class="form-inline ml-3">
    <div class="input-group input-group-sm">
     <input 
        hx-target="#typeahead-results"  
        hx-get="{% url "main:search" %}"
        hx-swap="innerHTML show:window:top"
        hx-trigger="keyup changed delay:200ms" 
        hx-include="[name='type']"
        name="q" 
        value="{{ request.GET.q }}"
        class="form-control form-control-navbar" 
        type="search" 
        placeholder="Buscar Socio" 
        aria-label="Buscar">
      <div class="input-group-append">
        <button class="btn btn-navbar" type="submit">
          <i class="fas fa-search"></i>
        </button>
      </div>
    </div>
</form>