bot/urls.py
from django.urls import path
from bot.views import *

app_name = 'bot'

urlpatterns = [
    path('', UpdateBot.as_view(), name='update'),
    path('send/<str:user_id>/', user_send_message, name='send_message'), #type:ignore
    path('send/<str:user_id>/pedido/<str:pedido_id>/', enviar_detalle_pedido, name='send_pedido'), #type:ignore
]

pedidos/urls.py
from django.urls import path
from pedidos.views import *

app_name = 'pedidos'

urlpatterns = [
    path('', lista_pedidos, name='lista'),
    path('hx/', lista_pedidos, name='hx-lista'),
    path('crear/', crear_pedido, name='crear'),
    path('detail/<str:id_pedido>/', pedido_crud_view, name='detail'),
    path('hx/crear/<str:id_operador>/', crear_pedido_hx, name='hx-crear'),
    path('hx/pedidoitem/pedido/<str:pedido_id>/add/', pedidoitem_crud_view, name='hx-add-item'),
    path('hx/pedidoitem/item/<str:item_id>/delete/', pedidoitem_crud_view, name='hx-delete-item'),
    path('hx/list_pedidos_by_operador/<str:id_operador>/', list_pedidos_by_operador, name='list-by-operador'),
    
    
]

pedidos/models.py
from decimal import Decimal
from django.db.models import * # type: ignore
from django.conf import settings
from django.urls import reverse
from productos.models import Categoria, Detalles, PrecioDistribuidor, PrecioClientePreferente
from socios.models import Operador
import datetime
import logging

User = settings.AUTH_USER_MODEL

class PedidoStatus(TextChoices):

    ENTREGADO = 'e', 'Entregado'
    CANCELADO = 'c', 'Cancelado'
    PENDIENTE = 'p', 'Pendiente'
    VENCIDO = 'v', 'Vencido'

class PedidoQuerySet(QuerySet):

    def by_user_id(self, user_id):
        return self.filter(user_id=user_id)

    def by_usuario(self, usuario):
        return self.filter(usuario=usuario)

    def by_operador(self, operador):
        return self.filter(operador=operador)

    def by_operador_id(self, operador_id):
        return self.filter(operador_id=operador_id)

    def by_pedidos_entregados(self, operador_id):
        return self.filter(operador_id=operador_id, status=PedidoStatus.ENTREGADO)

    def candelado(self):
        return self.filter(status=PedidoStatus.CANCELADO)
        
    def entregado(self):
        return self.filter(status=PedidoStatus.ENTREGADO)

    def pendiente(self):
        return self.filter(status=PedidoStatus.PENDIENTE)

    def vencido(self):
        return self.filter(status=PedidoStatus.VENCIDO)

class PedidoManager(Manager):
    def get_queryset(self):
        return PedidoQuerySet(self.model, using=self._db)

    def by_operador(self, operador):
        return self.get_queryset().by_operador(operador)

    def get_pedidos_entregados(self, operador):
        return self.get_queryset().by_pedidos_entregados(operador)

class Pedido(Model):
    
    usuario = ForeignKey(User, on_delete=CASCADE)
    operador = ForeignKey(Operador, on_delete=CASCADE)
    timestamp = DateTimeField(auto_now_add=True)
    updated = DateTimeField(auto_now=True)
    status = CharField(max_length=1, choices=PedidoStatus.choices, default=PedidoStatus.PENDIENTE)
    pedido_id = CharField(max_length=200)
    total_final = DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)

    objects = PedidoManager()

    def get_all_items(self):
        return self.pedidoitem_set.all() # type: ignore

    @property
    def get_cart_total(self) -> Decimal:
        """
        Calcula el costo total de todos los productos
        asociados al pedido, considerando el nivel del operador.
        Returns:
            Decimal: El costo total redondeado a dos decimales.
        """
        try:
            # Determinar el nivel del operador
            nivel_operador = self.operador.get_nivel_licencia  
            # Calcular el costo total de los ingredientes herbales
            costo_total = Decimal('0.00')
            for item in self.get_all_items():
                costo_producto = item.get_total(nivel=nivel_operador)
                if costo_producto is not None:
                    costo_total += Decimal(costo_producto)
            return costo_total
        except Exception as e:
            # Registrar el error
            logging.error(f"Error al calcular get_sobre_rojo: {e}")
            return Decimal('0.00')

    @property
    def get_cart_items(self):
        pedidoitems = self.pedidoitem_set.all() # type: ignore
        total = sum([item.cantidad for item in pedidoitems])
        return total

    @property
    def get_cart_points(self):
        pedidoitems = self.pedidoitem_set.all() # type: ignore
        total = round(sum([item.get_vol_points for item in pedidoitems]), 2)
        return total

    def get_absolute_url(self):
        return reverse("pedidos:detail", kwargs={"id_pedido": self.pedido_id})

    def save(self, *args, **kwargs):
        self.pedido_id = datetime.datetime.now().timestamp()
        if self.status == PedidoStatus.ENTREGADO:
            self.total_final = self.get_cart_total
        super().save(*args, **kwargs)

    def __str__(self):
        return str(self.operador)

class PedidoItem(Model):

    pedido = ForeignKey(Pedido, on_delete=CASCADE)
    categoria = ForeignKey(Categoria, on_delete=CASCADE, null=True)
    detalles = ForeignKey(Detalles, on_delete=CASCADE)
    cantidad = IntegerField(default=1)
    timestamp = DateTimeField(auto_now_add=True)
    updated = DateTimeField(auto_now=True)

    def get_total(self, nivel='Mayorista'):
        nivel_to_atributo = {
            'Mayorista': ('PrecioDistribuidor', 'mayorista'),
            'Productor Calificado': ('PrecioDistribuidor', 'productor_calificado'),
            'Consultor Mayor': ('PrecioDistribuidor', 'consultor_mayor'),
            'Distribuidor': ('PrecioDistribuidor', 'distribuidor'),
            'Oro': ('PrecioClientePreferente', 'oro'),
            'Plata': ('PrecioClientePreferente', 'plata'),
            'Bronce': ('PrecioClientePreferente', 'bronce'),
            'Cliente': ('PrecioClientePreferente', 'cliente'),
        }
        try:
            nivel = self.pedido.operador.get_nivel_licencia
        except:
            pass

        if nivel not in nivel_to_atributo:
            raise ValueError(f"Nivel '{nivel}' no es válido.")

        modelo, atributo = nivel_to_atributo[nivel]

        if modelo == 'PrecioDistribuidor':
            precio_obj = PrecioDistribuidor.objects.filter(
                categoria=self.categoria, activo=True
            ).order_by('-inserted_on').first()
        elif modelo == 'PrecioClientePreferente':
            precio_obj = PrecioClientePreferente.objects.filter(
                categoria=self.categoria, activo=True
            ).order_by('-inserted_on').first()

        if not precio_obj:
            raise ValueError(f"No se encontró un precio activo para la categoría '{self.categoria}' y nivel '{nivel}'.")

        precio = getattr(precio_obj, atributo, None)
        if precio is None:
            raise ValueError(f"El atributo '{atributo}' no existe o es nulo para el nivel '{nivel}'.")

        total = precio * self.cantidad

        return total

    @property
    def get_vol_points(self):
        puntos = round(self.categoria.puntos_volumen * self.cantidad, 2) # type: ignore
        return puntos

    def get_delete_url(self):
        return reverse('pedidos:hx-delete-item', kwargs={'item_id': self.pk})

    def __str__(self):
        return str(self.pedido)

pedidos/forms.py
from django import forms
from django.urls import reverse
from pedidos.models import *
from productos.models import Categoria

class PedidoForm(forms.ModelForm):
    
    class Meta:
        model = Pedido
        fields = ['operador']
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            field_name = str(field)
            new_data = {
                'class' : 'form-control',
            }
            self.fields[field_name].widget.attrs.update(new_data)


class PedidoItemModelForm(forms.ModelForm):
    required_css_class = "required-field"
    ProductosFormSet = forms.modelformset_factory(Categoria, fields=('nombre', 'detalle', 'cantidad'))
    formset = ProductosFormSet(queryset=Categoria.objects.interna())

    class Meta:
        model = PedidoItem
        fields = ['categoria', 'detalles', 'cantidad']
        

    def get_flavor_url(self):
        return reverse('productos:hx-sabores')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            field_name = str(field)
            new_data = {
                'class' : 'form-control',
            }
            self.fields[field_name].widget.attrs.update(new_data)

        self.fields['categoria'].widget.attrs.update(
            {
                'hx-get': self.get_flavor_url(),
                'hx-trigger': 'change',
                'hx-target': '#id_detalles',
            
            }
            )
        self.fields['categoria'].queryset = Categoria.objects.interna()

class PedidoItemForm(forms.Form):

    f = {}

    categoria = forms.CharField(label='Categoria', max_length=10, required=False)  #type:ignore
    detalles = forms.ComboField(fields=f) #type:ignore
    cantidad = forms.CharField(label='Cantidad', max_length=3) #type:ignore

    class Meta:
        fields = ['categoria', 'detalles', 'cantidad']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            field_name = str(field)
            new_data = {
                'class' : 'form-control',
            }
            self.fields[field_name].widget.attrs.update(new_data)

        self.fields['categoria'].widget.attrs.update(
            {
                'hx-get': 'sabores/',
                'hx-trigger': 'change',
                'hx-target': '#id_detalles',
            
            }
            )

pedidos/views.py
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import HttpResponse, Http404
from django.shortcuts import render, get_object_or_404
from home.decorators import allowed_users
from icecream import ic
from pedidos.forms import *
from pedidos.models import *
ic.disable()
def lista_pedidos(request):
    context, template = {}, 'apps/pedidos/list.html'
    obj_list = Pedido.objects.all().order_by('-timestamp')
    if request.htmx:
        obj_list = obj_list[:5]
        template = 'apps/pedidos/partials/list.html'
    
    context['obj_list'] = obj_list

    return render(request, template, context)

def crear_pedido_hx(request, id_operador=None):
    context, template = {}, 'apps/pedidos/partials/list.html'
    
    if request.method == 'POST':
        operador = get_object_or_404(Operador, id=id_operador)
        pedido = Pedido.objects.create(
            usuario = request.user,
            operador = operador
        )
        if request.htmx:
            headers = {"HX-Redirect": pedido.get_absolute_url()}
            return HttpResponse("Created", headers=headers)
        
    obj_list = Pedido.objects.filter(operador=id_operador).order_by('-timestamp')[:5]
    context = {'obj_list': obj_list, 'id_operador': id_operador}
        
    return render(request, template, context)

def pedido_crud_view(request, id_pedido=None, id_operador=None):
    context, template = {}, 'apps/pedidos/detail.html'
    pedido = get_object_or_404(Pedido, pedido_id=id_pedido)

    context['parent_obj'] = pedido
        
    if request.method == 'POST' and id_operador: 
        pedido = Pedido.objects.create(
            usuario = request.user,
            operador = Operador.objects.get(id=id_operador)
        )
        headers = {"HX-Redirect": pedido.get_absolute_url()}
        return HttpResponse("Created", headers=headers)

    if request.method == 'PUT':
        # pedido = Pedido.objects.get(pedido_id=id_pedido)
        pedido.status = PedidoStatus.ENTREGADO
        pedido.save()
        headers = {"HX-Redirect": pedido.get_absolute_url()}
        return HttpResponse("Updated", headers=headers)
    
    if request.method == 'DELETE':
        # pedido = Pedido.objects.get(pedido_id=id_pedido)
        pedido.status = PedidoStatus.CANCELADO
        pedido.save()
        headers = {"HX-Redirect": pedido.get_absolute_url()}
        return HttpResponse("Updated", headers=headers)

    context['form'] = PedidoItemModelForm

    return render(request, template, context)


def hx_update_status(parent_obj, status):
    parent_obj.status = status
    parent_obj.save()
    headers = {"HX-Redirect": parent_obj.get_absolute_url()}
    return HttpResponse("OK", headers=headers)

def crear_pedido(request):
    context, template = {}, 'apps/pedidos/crear.html'
    form = PedidoForm(request.POST or None)
    context['form'] = form
    pedido_item_form = PedidoItemModelForm(request.POST or None)
    context['pedido_item_form'] = pedido_item_form
    
    if form.is_valid():
        print(f"form: {form}")
    if pedido_item_form.is_valid():
        print(f"pedido_item_form: {pedido_item_form}")
    return render(request, template, context)



def pedidoitem_crud_view(request, pedido_id=None, item_id=None):
    context, template = {}, 'apps/pedidos/partials/table-form.html'
    try:
        pedido = Pedido.objects.get(pedido_id=pedido_id)
    except Pedido.DoesNotExist:
        pedido = PedidoItem.objects.get(id=item_id).pedido

    if request.method == 'POST':
        form = PedidoItemModelForm(request.POST or None)
        if form.is_valid():
            categoria_id = request.POST.get('categoria')
            detalles_id = request.POST.get('detalles')
            obj, created = PedidoItem.objects.get_or_create(
                pedido = Pedido.objects.get(pedido_id=pedido_id),
                categoria = Categoria.objects.get(id=categoria_id),
                detalles = Detalles.objects.get(id=detalles_id),
                defaults={
                    'cantidad': request.POST.get('cantidad'),
            })
            if not created:
                obj.cantidad += int(request.POST.get('cantidad'))
                obj.save()
        
    
            # context = {
            #     'parent_obj': obj.pedido,
            #     'form': PedidoItemModelForm
            # }

    if request.method == "DELETE":
        try:
            obj = PedidoItem.objects.get(id=item_id)
        except:
            obj = None
        if obj is None:
            if request.htmx:
                return HttpResponse("Not Found")
            raise Http404
        
        context['msg'] = f"Se eliminó: {obj.cantidad} {obj.categoria} de {obj.detalles}"
        obj.delete()

    # allow = True if pedido.get_all_items() and bot_user_id else False
    context = {
                'parent_obj': pedido,
                # 'allow': allow,
                # 'user_id': bot_user_id,
                'form': PedidoItemModelForm
            }
    
            
    return render(request, template, context)

class PedidoStatus:
    PENDIENTE = 'p'
    ENTREGADO = 'e'

@allowed_users(['admin', 'operadores'])
def list_pedidos_by_operador(request, id_operador=None):
    context, template = {}, 'apps/pedidos/list.html'
    operador = get_object_or_404(Operador, pk=id_operador)
    
    # Filter and order pedidos
    pedidos = operador.pedido_set.filter(
        status__in=[PedidoStatus.PENDIENTE, PedidoStatus.ENTREGADO]
    ).order_by('-timestamp')
    
    # Handle HTMX requests
    if request.htmx:
        pedidos = pedidos[:5]
        ic(pedidos)
        template = 'apps/pedidos/partials/list.html'

    # Safely retrieve bot_user_id
    bot_user_id = (
        operador.licencia.persona.get_bot_id
        if operador.licencia and operador.licencia.persona
        else None
    )
    ic(bot_user_id)
    # Build context
    context = {
        'obj_list': pedidos,
        'operador': operador,
        'bot_user_id': bot_user_id,
    }
    ic(context)
    return render(request, template, context)

templates/apps/pedidos/partials/forms.html
<form role="form" action="." method="POST" hx-post="." hx-target="#recipe-container" hx-swap="outerHTML" hx-trigger="{% if form.instance.id %}change delay:500ms, {% endif %}submit">
    {% csrf_token %}
    <div class="card-body">
      {% if message  %}
        <div class="ribbon-wrapper ribbon-lg">
          <div class="ribbon bg-success text-lg">
            {{ message }}
          </div>
        </div>
      {% endif %}
      
      {% for field in form %}
        <div class="form-group {% if field.field.required %}{{ form.required_css_class}}{% endif %}">
          {{ field.label_tag }} {% if field.field.required %}*{% endif %}
          {{ field }}
          {% if field.help_text %}
            <p class="help"> {{ field.help_text|safe }}</p>
          {% endif %}
        </div>
      {% endfor %}

      {% for field in pedido_item_form %}
        <div class="form-group {% if field.field.required %}{{ form.required_css_class}}{% endif %}">
          {{ field.label_tag }} {% if field.field.required %}*{% endif %}
          {{ field }}
          {% if field.help_text %}
            <p class="help"> {{ field.help_text|safe }}</p>
          {% endif %}
        </div>
      {% endfor %}
    </div>
    <!-- /.card-body -->

    <div class="card-footer">
      <button type="submit" class="btn btn-primary">Guardar</button>
    </div>
</form>

templates/apps/pedidos/partials/item-deleted.html
{% comment %} <div class="card-body"> {% endcomment %}
  {% if messages %}
  {% for message in messages %}
  <div class="card bg-gradient-danger collapsed-card">
    <div class="card-header">
      <h3 class="card-title">{{ message }}</h3>
      <div class="card-tools">
        <button type="button" class="btn btn-tool" data-card-widget="remove"><i class="fas fa-times"></i>
        </button>
      </div>
    </div>
  </div>
  {% endfor %}
  {% else %}
  <div class="card bg-gradient-danger collapsed-card">
    <div class="card-header">
      <h3 class="card-title">{{ msg }}</h3>
      <div class="card-tools">
        <button type="button" class="btn btn-tool" data-card-widget="remove"><i class="fas fa-times"></i>
        </button>
      </div>
    </div>
  </div>
  {% endif %}
{% comment %} </div> {% endcomment %}

templates/apps/pedidos/partials/list.html
<div class="card">
  <div class="card-header">
    <h3 class="card-title">Pedidos</h3>
  </div>
  <!-- ./card-header -->
  <div class="card-body p-0">
    <div class="table-responsive">
      <table class="table table-hover text-nowrap m-0">
        <thead>
        <tr>
          <th>Fecha</th>
          <th>Operador</th>
          <th>Status</th>
          <th>Total</th>
          <th>Pagado</th>
  
        </tr>
        </thead>
        <tbody>
        {% for obj in obj_list %}
          <tr data-widget="expandable-table" aria-expanded="false"
          _="on click toggle the *display of the next <p/>
            toggle .d-none on the next <tr/>">
            <td><a href="{{ obj.get_absolute_url }}">{{ obj.timestamp }}</a></td>
            <td>{{ obj.operador }}</td>
            {% if obj.status == 'p' %}
              <td><span class="badge badge-warning">Pendiente</span></td>
            {% elif obj.status == 'e' %}
              <td><span class="badge badge-success">Entregado</span></td>
            {% elif obj.status == 'c' %}
              <td><span class="badge badge-danger">Cancelado</span></td>
            {% elif obj.status == 'v' %}
              <td><span class="badge badge-info">Vencido</span></td>               
            {% endif %}
            <td>{{ obj.get_cart_total }}</td>
            <td>{{ obj.total_final }}</td>
          </tr>
          <tr class="expandable-body d-none">
            <td colspan="4">
              <p style="display: none;">
                <ul>
                  {% for item in obj.get_all_items %}
                  <li>{{ item.categoria }} {{ item.detalles }} x {{ item.cantidad }}</li>
                  {% endfor %}
                </ul>
              </p>
            </td>
            <td>
              {% if obj.get_all_items %}
                {% include 'apps/pedidos/partials/send_order.html' %}
              {% endif %}
            </td>
          </tr>
        {% empty %}
          <tr>
            <td>...</td>
            <td>...</td>
            <td><span class="badge badge-danger">Vacio</span></td>
            <td>...</td>
          </tr>
        {% endfor %}
        </tbody>
      </table>
    </div>
    <!-- /.table-responsive -->
  </div>
  <!-- /.card-body -->
  {% if operador %}
    <div class="card-footer clearfix">
      <a class="btn btn-sm btn-info float-left"
      hx-post="{% url 'pedidos:hx-crear' id_operador=operador.pk %}" 
      >Nuevo Pedido</a>
      <a href="{% url 'pedidos:list-by-operador' operador.pk %}" class="btn btn-sm btn-secondary float-right">Todos los Pedidos</a>
    </div>
  {% endif %}
  <!-- /.card-footer -->
</div>

templates/apps/pedidos/partials/sabores.html
{% extends 'base.html' %}

{% block main-content %}

{% endblock main-content %}

templates/apps/pedidos/partials/send_order.html
{% comment %} <a href="#" 
    class="btn btn-tool btn-sm"
    hx-get = {% url 'bot:send_pedido' user_id=user_id pedido_id=parent_obj.pedido_id %}
    hx-swap = outerHTML
    hx-success = "swal('Exito!', 'El mensaje se envió correctamente', 'success')"
    hx-error = "swal('Error!', 'Error al enviar el mensaje', 'error')">
    {% if sended %}<i class="fas fa-check"></i>{% else %}<i class="fas fa-comment-dollar"></i>{% endif %}
    
</a> {% endcomment %}

<a class="btn btn-app bg-info"
    hx-get = {% url 'bot:send_pedido' user_id=bot_user_id pedido_id=obj.pedido_id %}
    hx-swap = outerHTML>
    <span class="badge bg-danger">{{ obj.get_all_items.count }}</span>
    {% if sended %}<i class="fas fa-check"></i> Enviado{% else %}<i class="fab fa-telegram"></i> Enviar{% endif %}
</a>

templates/apps/pedidos/partials/table-form.html
{% load static %}
<div class="card-header border-0">
  
  <h3 class="card-title">Fecha: {{ parent_obj.updated|date }}</h3>
  <div class="card-tools">
    {% if allow %}
    {% include 'apps/pedidos/partials/send_order.html' %}
    {% endif %}
    <a href="javascript:void(0)" class="btn btn-tool btn-sm">
      <i class="fas fa-bars"></i>
    </a>
  </div>
</div>
<div class="card-body p-0" >
  
  {% if msg %}
    {% include 'apps/pedidos/partials/item-deleted.html' %}
  {% endif %}
  <div class="card">
    <div class="card-body p-0">
      {% if parent_obj.status == 'c' %}
      <div class="ribbon-wrapper ribbon-xl">
        <div class="ribbon bg-danger">
          Cancelado
        </div>
      </div>
      {% elif parent_obj.status == 'e' %}
        <div class="ribbon-wrapper ribbon-xl">
          <div class="ribbon bg-success">
            Entregado
          </div>
        </div>
      {% endif %}
      
      <table class="table table-striped table-valign-middle">
        <thead>
          <tr>
            <th></th>
            <th>Cant.</th>
            <th>P.Vol.</th>
            <th>Precio</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><strong>Totales</strong></td>
            {% if parent_obj.get_cart_items %}<td>{{ parent_obj.get_cart_items }}</td>{% else %}<td>...</td>{% endif %}
            {% if parent_obj.get_cart_points %}<td>{{ parent_obj.get_cart_points }}</td>{% else %}<td>...</td>{% endif %}
            {% if parent_obj.get_cart_total %}<td>{{ parent_obj.get_cart_total }}</td>{% else %}<td>...</td>{% endif %}
            <td></td>
          </tr>
          {% for obj in parent_obj.get_all_items %}
            <tr id="item-{{obj.id}}">
              <td>{{ obj.categoria }} <ion-icon name="arrow-dropright"></ion-icon> {{ obj.detalles }}</td>
              <td>{{ obj.cantidad }}</td>
              <td>{{ obj.get_vol_points }}</td>
              <td>{{ obj.get_total }}</td>
              {% if parent_obj.status == 'p' %}
              <td>
                <button type="button" class="btn btn-danger btn-xs"
                  hx-delete="{{ obj.get_delete_url }}"
                  hx-confirm="¿Realmente quieres eliminar '{{ obj.cantidad }} {{ obj.categoria }} {{ obj.detalles }}'?"
                  hx-target="#table-and-form">
                  <i class="fas fa-trash"></i>
                </button>
              </td>
              {% else %}
              <td></td>
            </tr>
            {% endif %}
          {% empty %}  
          <tr>
            <td>Sin Datos</td>
            <td>...</td>
            <td>...</td>
            <td>...</td>
            <td></td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>

  {% if parent_obj.status == 'p' %}
  <div class="card">
    <div class="card-body">
      
      <form hx-post="{% url 'pedidos:hx-add-item' pedido_id=parent_obj.pedido_id  %}" hx-target="#table-and-form">
        {% csrf_token %}
          {% for field in form %}
            <div class="form-group{% if field.field.required %} {{ form.required_css_class}}{% endif %}">
              {{ field.label_tag }} {% if field.field.required %}*{% endif %}
              {{ field }}
              {% if field.help_text %}
                <p class="help"> {{ field.help_text|safe }}</p>
              {% endif %}
            </div>
          {% endfor %}
          <div class="form-group">
              <button id="btn_submit" type="submit" class="btn btn-primary btn-block">Agregar</button>
          </div>
      </form>
    
    </div>
  </div>
  {% endif %}
  {% if parent_obj.status == 'p' and parent_obj.get_cart_items %}
  <div class="card-footer">
    <button 
      type="submit" 
      class="btn btn-danger"
      hx-delete="{{ parent_obj.get_absolute_url }}"
      hx-confirm="¿Realmente deseas eliminar éste Pedido?">
      Eliminar Pedido
    </button>
    <button 
      type="submit" 
      class="btn btn-success float-right"
      hx-put="{{ parent_obj.get_absolute_url }}"
      hx-confirm="¿El Pedido ha sido ENTREGADO?">
      Pedido Entregado
    </button>
  </div>
  {% endif %}
</div>