bot/urls.py
from django.urls import path
from bot.views import *

app_name = 'bot'

urlpatterns = [
    path('', UpdateBot.as_view(), name='update'),
    path('send/<str:user_id>/', user_send_message, name='send_message'), #type:ignore
    path('send/<str:user_id>/pedido/<str:pedido_id>/', enviar_detalle_pedido, name='send_pedido'), #type:ignore
]

comanda/urls.py
from django.urls import path
from comanda.views import *

app_name = 'comanda'

urlpatterns = [
    path('', comanda_view, name='form'),
    path('hx/comanda/<str:id_socio>/create/', hx_create_comanda_view, name='hx-create-comanda'), #type:ignore
    path('hx/comanda/<str:id_comanda>/prepago/<str:id_prepago>', hx_add_prepago_view, name='hx-add-prepago'), #type:ignore
    path('hx/<str:id_comanda>/status/update/', hx_update_status, name='hx-update-status'), #type:ignore
    path('hx/admin/<str:id_comanda>/status/update/', hx_admin_update_status, name='hx-admin-update-status'), #type:ignore
    path('hx/comanda/item/<int:id_comanda_item>/edit/', comanda_item_edit_view, name='hx-edit-item'), #type:ignore
    path('hx/comanda/<str:id_comanda>/receta/<str:id_receta>/delete/', hx_crud_comandaitem_view, name='hx-crud-comanda-item'), #type:ignore
]

consumos/urls.py
from django.urls import path
from consumos.views import list_consumos_by_id_operador, create_delete_transferencia

app_name = 'consumos'

urlpatterns = [
    path('by_id_operador/<str:id_operador>/', list_consumos_by_id_operador, name='by-id-operador' ),
    path('hx/consumo/<str:id_consumo>/add_delete_transferencia/', create_delete_transferencia, name='crud_transferencia')
]

comanda/models.py
from decimal import Decimal
from django.db.models import *
from django.conf import settings
from django.urls import reverse
from django.core.cache import cache
from django.utils.timezone import now
from django.db.models import Sum, F, Q
from django.db.models.functions import Coalesce
from main.models import Settings
from recetas.models import Receta
from socios.models import Socio
from prepagos.models import Prepago
import logging

User = settings.AUTH_USER_MODEL


def get_setting_value(name, default=0):
    """Utility to fetch settings with caching."""
    cache_key = f"setting_{name}"
    value = cache.get(cache_key)
    if value is None:
        try:
            value = int(Settings.objects.get(nombre=name).valor)
        except Settings.DoesNotExist:
            value = default
        cache.set(cache_key, value, timeout=3600)  # Cache for an hour
    return value


class ComandaStatus(TextChoices):
    ENTREGADO = 'e', 'Entregado'
    CANCELADO = 'c', 'Cancelado'
    PENDIENTE = 'p', 'Pendiente'
    VENCIDO = 'v', 'Vencido'


class ComandaQuerySet(QuerySet):
    def by_user_id(self, user_id):
        return self.filter(id=user_id)

    def by_user(self, usuario):
        return self.filter(usuario=usuario)

    def cancelado(self):
        return self.filter(status=ComandaStatus.CANCELADO)

    def entregado(self):
        return self.filter(status=ComandaStatus.ENTREGADO)

    def pendiente(self):
        return self.filter(status=ComandaStatus.PENDIENTE)

    def vencido(self):
        return self.filter(status=ComandaStatus.VENCIDO)

    def annotated_totals(self):
        return self.annotate(
            cart_total=Sum(F('comandaitem__cantidad') * F('comandaitem__receta__precio_publico')),
            cart_points=Sum(F('comandaitem__cantidad') * F('comandaitem__receta__get_cart_points')),
        )


class ComandaManager(Manager):
    def get_queryset(self):
        return ComandaQuerySet(self.model, using=self._db)


class Comanda(Model):
    fecha = DateField(default=now)
    usuario = ForeignKey(User, on_delete=CASCADE)
    socio = ForeignKey(Socio, on_delete=CASCADE)
    prepago = ManyToManyField(Prepago, blank=True)
    timestamp = DateTimeField(auto_now_add=True)
    updated = DateTimeField(auto_now=True)
    status = CharField(max_length=1, choices=ComandaStatus.choices, default=ComandaStatus.PENDIENTE)

    objects = ComandaManager()

    @property
    def get_add_receta_url(self):
        return reverse('comanda:hx-crud-comanda-item', kwargs={'id_comanda': self.pk, 'id_receta': None})

    @property
    def get_uniq_prepagos_list(self):
        socio_prepagos = self.socio.prepago_set.filter(activo=True)
        comanda_prepagos = self.prepago.all()
        return list(socio_prepagos.union(comanda_prepagos))

    @property
    def get_total_descuento(self):
        return round(sum(item.descuento_decimal for item in self.get_cart_prepagos), 2)

    @property
    def get_cart_prepagos(self):
        return self.prepago.all()
    
    @property
    def get_sobre_rojo(self) -> Decimal:
        """
        Calcula el costo total de los ingredientes herbales de todas las recetas
        asociadas a la comanda, considerando el nivel del operador.
        Returns:
            Decimal: El costo total redondeado a dos decimales.
        """
        try:
            # Verificar si el socio tiene un operador asociado
            # y si el operador tiene un nivel de licencia
            # Si no hay operador o no tiene nivel, retornar 0
            if not hasattr(self, 'socio') or not hasattr(self.socio, 'operador'):
                return Decimal('0.00')
            
            # Determinar el nivel del operador
            nivel_operador = self.socio.operador.get_nivel_licencia  
            # Calcular el costo total de los ingredientes herbales
            costo_total = Decimal('0.00')
            for item in self.comandaitem_set.select_related('receta').all():
                receta = item.receta
                for ing_herb in receta.get_herbal_ingredient_children():
                    costo_ingrediente = ing_herb.get_costo(nivel=nivel_operador)
                    if costo_ingrediente is not None:
                        costo_total += Decimal(costo_ingrediente)

            # Obtener el porcentaje de reinversión desde Settings
            porciento_inversion = Decimal(get_setting_value('inversion', 10))

            # Calcular la reinversión
            re_inversion = self.porcentaje(costo_total, porciento_inversion)

            # Sumar el costo total y la reinversión
            sobre_rojo_final = (costo_total + re_inversion).quantize(Decimal('0.00'))

            return sobre_rojo_final
        except Exception as e:
            # Registrar el error
            logging.error(f"Error al calcular get_sobre_rojo: {e}")
            return Decimal('0.00')

    # @property
    # def get_cart_total(self):
    #     return self.get_all_items().aggregate(
    #         total=Sum(F('cantidad') * F('receta__precio_publico'))
    #     )['total'] or 0

    @property
    def get_cart_total(self):
        return self.get_all_items().aggregate(
            total=Coalesce(Sum(F('cantidad') * F('receta__precio_publico')), Decimal('0.00'))
        )['total']

    @property
    def get_mantenimiento(self):
        mant = get_setting_value('mantenimiento', 10)
        return self.porcentaje(self.get_cart_total, mant)

    @property
    def get_insumos(self):
        items = self.get_all_items()
        total = sum(item.get_insumos for item in items) if items else 0

        # Obtener el valor de insumos desde Settings
        insumos = get_setting_value('insumos', 0) if items else 0
        total += insumos

        return Decimal(total).quantize(Decimal('0.00'))

    @property
    def get_cart_count_items(self):
        return self.get_all_items().aggregate(
            total=Coalesce(Sum('cantidad'), 0)
        )['total']

    @property
    def get_cart_points(self):
        return round(sum(item.get_puntos for item in self.get_all_items()), 2)

    @property
    def get_cart_cash(self):
        if self.is_operador():
            efectivo = round(self.get_mantenimiento + self.get_insumos + self.get_sobre_rojo, 2)
        else:
            efectivo = self.get_cart_total - sum(prepago.valor for prepago in self.prepago.all())
        return max(Decimal(efectivo).quantize(Decimal('0.00')), Decimal('0.00'))

    @property
    def get_sobre_verde(self):
        """
        Calcula el valor de 'sobre verde' restando los costos totales del total del carrito.
        Returns:
            Decimal: El valor de 'sobre verde', redondeado a dos decimales.
        """
        if self.is_operador():
            return Decimal('0.00')

        # Convertir todos los valores a Decimal y manejar valores nulos
        sobre_rojo = Decimal(self.get_sobre_rojo).quantize(Decimal('0.00'))
        total_descuento = Decimal(self.get_total_descuento).quantize(Decimal('0.00'))
        insumos = Decimal(self.get_insumos).quantize(Decimal('0.00'))
        mantenimiento = Decimal(self.get_mantenimiento).quantize(Decimal('0.00'))
        print(f"Sobre rojo: {sobre_rojo}, Total descuento: {total_descuento}, Insumos: {insumos}, Mantenimiento: {mantenimiento}")
        # Calcular la suma de costos
        costos = (sobre_rojo + total_descuento + insumos + mantenimiento).quantize(Decimal('0.00'))

        # Calcular el valor de 'sobre verde'
        cart_total = Decimal(self.get_cart_total).quantize(Decimal('0.00'))
        sobre_verde = (cart_total - costos).quantize(Decimal('0.00'))

        return sobre_verde

    def is_operador(self):
        try:
            return self.socio.persona.licencia.operador
        except AttributeError:
            return False

    def get_all_items(self):
        return self.comandaitem_set.all()

    def porcentaje(self, total: Decimal, porciento: float) -> Decimal:
        """
        Calcula el porcentaje de un valor dado.
        Args:
            total (Decimal): El valor base.
            porciento (float): El porcentaje a calcular.
        Returns:
            Decimal: El resultado del cálculo, redondeado a dos decimales.
        """
        return (total * Decimal(porciento) / 100).quantize(Decimal('0.00'))

    # def porcentaje(self, total, porciento):
    #     return total * porciento / 100

    def __str__(self):
        return str(self.socio)

    class Meta:
        constraints = [
            CheckConstraint(check=~Q(status=''), name='status_not_empty'),
        ]


class ComandaItem(Model):
    comanda = ForeignKey(Comanda, on_delete=CASCADE)
    receta = ForeignKey(Receta, on_delete=SET_NULL, null=True, blank=True)
    cantidad = IntegerField(default=1, blank=True, null=True)
    timestamp = DateTimeField(auto_now_add=True)
    updated = DateTimeField(auto_now=True)

    @property
    def get_puntos(self):
        try:
            return round(self.cantidad * self.receta.get_cart_points, 2)
        except AttributeError:
            return 0

    @property
    def get_total(self):
        try:
            return round(self.cantidad * self.receta.precio_publico, 1)
        except AttributeError:
            return 0

    @property
    def get_costo(self):
        try:
            return round(self.cantidad * self.receta.get_costo_receta, 1)
        except AttributeError:
            return 0

    @property
    def get_insumos(self):
        try:
            return round(self.cantidad * self.receta.get_insumos, 1)
        except AttributeError:
            return 0

    @property
    def get_sobre_rojo(self):
        try:
            return round(self.cantidad * self.receta.get_sobre_rojo, 1)
        except AttributeError:
            return 0

    def get_crud_url(self):
        return reverse('comanda:hx-crud-comanda-item', kwargs={'id_receta': self.pk, 'id_comanda': self.comanda.pk})

    def get_edit_url(self):

comanda/forms.py
from django.forms import * #type: ignore
from django.urls import reverse
from comanda.models import Comanda, ComandaItem
from prepagos.models import Prepago
from recetas.models import Receta

class ComandaItemForm(ModelForm):

    receta = ModelChoiceField(Receta.objects.all().order_by('nombre'))

    required_css_class = "required-field"
    class Meta:
        model = ComandaItem
        fields = ['receta', 'cantidad']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            field_name = str(field)
            new_data = {
                'class' : 'form-control',
            }
            self.fields[field_name].widget.attrs.update(new_data)


class ComandaForm(Form):

    new_data = {
        'class' : 'form-control',
        'type' : 'date',
    }
    
    fecha = DateField(widget=DateInput(attrs=new_data))

class ComandaModelForm(ModelForm):
    new_data = {
        'class' : 'form-control',
        'type' : 'date',
    }
    
    fecha = DateField(widget=DateInput(attrs=new_data))
    class Meta:
        model = Comanda
        fields = ['fecha', 'prepago']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        comanda_ = args[0]['comanda']
        prepagos_ = args[0]['prepagos']
        for field in self.fields:
            field_name = str(field)
            new_data = {
                'class' : 'form-control',
                
            }
            self.fields[field_name].widget.attrs.update(new_data)
            # print(Prepago.get_prepagos_list)
        self.fields['prepago'].queryset = prepagos_
        self.fields['prepago'].widget.attrs.update(
            {
                'hx-get': '',
                'hx-trigger': 'change',
                'hx-target': '#total_a_pagar'
            }
        )

templates/apps/comanda/partials/comanda-item.html
<tr id="receta-{{ obj.id }}">
  <td><a href="{{ obj.receta.get_absolute_url }}">{{ obj }}</a></td>
  <td>{{ obj.cantidad }}</td>
  <td>{{ obj.get_puntos }}</td>
  <td>{{ obj.get_total }}</td>
  <td>
    <div class="btn-group">
      <button type="button" class="btn btn-danger btn-sm"
        data-url="{{ obj.get_crud_url }}"
        data-receta="{{ obj.receta }}"
        data-cantidad="{{ obj.cantidad }}"
        data-action="delete"
        hx-target="#comanda-list-and-form"
        >
        <i class="fas fa-trash"></i>
      </button>
      <button type="button" class="btn btn-info btn-sm"
        hx-put="{{ obj.get_crud_url }}"
        hx-target="#receta-{{ obj.id }}"
        >
        <i class="fas fa-edit"></i>
      </button>
    </div>
  </td>
</tr>

templates/apps/comanda/partials/comanda-nueva.html
<div class="card">
    <div class="card-header">
      <h3 class="card-title">Nuevo Consumo</h3>
    </div>
    <!-- /.card-header -->
    <div class="card-footer">
      <div class="form-group">
          <button type="button" class="btn btn-outline-success btn-flat btn-block"
          hx-post="{% url 'comanda:hx-create-comanda' id_socio=socio_obj.id %}"
          hx-target="#nuevo-consumo"
          >Crear</button>
      </div>
    </div>
</div>
<!-- /.card -->

templates/apps/comanda/partials/comanda-pendiente.html
<div class="card card-warning card-outline">
    <div class="card-header border-transparent">
        <h3 class="card-title">Nuevo Consumo ({{parent_obj.fecha | date:'d M Y - D' }})</h3>
        
        <div class="card-tools">
        <span class="badge {% if parent_obj.status == 'p' %} badge-warning{% elif parent_obj.status == 'e' %} badge-success{% else %} badge-danger{% endif %}">{{ parent_obj.status|upper }}</span>
        <button type="button" class="btn btn-tool" data-card-widget="collapse"><i class="fas fa-minus"></i>
        </button>
        </div>
        <!-- /.card-tools -->
    </div>
    <!-- /.card-header -->
    <div class="card-body p-0" id="comanda-list-and-form">
        {% include 'apps/comanda/partials/table-form.html' %}
    </div>
    <!-- /.card-body -->
    <div class="card-footer">
        <div class="form-group">
            <button type="button" class="btn btn-success btn-block"
            hx-get="{% url 'comanda:hx-update-status' id_comanda=parent_obj.id %}"
            hx-target="#error-message"
            >Pagada</button>
        </div>
    </div>
</div>
<!-- /.card -->

templates/apps/comanda/partials/desgloce.html
<div class="card card-warning collapsed-card" id="prepago-7">
    <div class="card-header">
      <h3 class="card-title">44.0 - ( Saldo: 13,0 )</h3>

      <div class="card-tools">
        <button type="button" class="btn btn-tool" data-card-widget="collapse"><i class="fas fa-plus"></i>
        </button>
      </div>
      <!-- /.card-tools -->
    </div>
    <div class="card-body p-0" style="display: none;">
      
      <table class="table table-striped table-valign-middle">
        <thead>
        <tr>
          <th>Fecha</th>
          <th>Monto</th>
          <th>Día</th>
        </tr>
        </thead>
        <tbody>
        
        <tr>
          <td>9 de Octubre de 2022</td>
          <td>50.0 Bs.</td>
          <td>Domingo</td>
        </tr>
        
        <tr>
          <td>9 de Octubre de 2022</td>
          <td>100.0 Bs.</td>
          <td>Domingo</td>
        </tr>
        
        <tr>
          <td>11 de Octubre de 2022</td>
          <td>33.0 Bs.</td>
          <td>Martes</td>
        </tr>
        
        <tr>
          <td>11 de Octubre de 2022</td>
          <td>10.0 Bs.</td>
          <td>Martes</td>
        </tr>
        
        <tr>
          <td>2 de Noviembre de 2022</td>
          <td>20.0 Bs.</td>
          <td>Miércoles</td>
        </tr>
        
        <tr>
          <td>3 de Noviembre de 2022</td>
          <td>30.0 Bs.</td>
          <td>Jueves</td>
        </tr>
        
        <tr>
          <td>3 de Noviembre de 2022</td>
          <td>50.0 Bs.</td>
          <td>Jueves</td>
        </tr>
        
        <tr>
          <td>3 de Noviembre de 2022</td>
          <td>30.0 Bs.</td>
          <td>Jueves</td>
        </tr>
        
        <tr>
          <td>13 de Noviembre de 2022</td>
          <td>10.0 Bs.</td>
          <td>Domingo</td>
        </tr>
        
        <tr>
          <td>23 de Diciembre de 2022</td>
          <td>50.0 Bs.</td>
          <td>Viernes</td>
        </tr>
        
        
        <tr>
          <form hx-post="/prepagos/add/pago/7/" hx-target="#prepago-7" hx-swap="outerHTML"></form>
            <input type="hidden" name="csrfmiddlewaretoken" value="0vhqtk2mUKPNfj3FmSTS8iPA2XidcOq6pab17GKxX5opaux60CvDFAUcj2cQmhix">
            
            <td><input type="text" name="fecha" value="29/01/2023 18:35:16" class="form-control" required="" id="id_fecha"><input type="hidden" name="initial-fecha" value="2023-01-29 18:35:16" id="initial-id_fecha"></td>
            
            <td><input type="number" name="monto" step="any" class="form-control" required="" id="id_monto"></td>
            
            <td><button id="btn_submit" type="submit" class="btn btn-primary">Agregar</button></td>
          
        </tr>
        
        </tbody>
      </table>
    </div>
</div>

templates/apps/comanda/partials/dollar.html
<span class="info-box-icon bg-success" id="icon-selected"><i class="fas fa-dollar-sign"></i></span>

templates/apps/comanda/partials/edit-form.html
<td colspan="5">
  <form hx-post="{{ obj.get_edit_url }}" hx-target="#comanda-list-and-form">
    {% csrf_token %}
    <div class="row align-items-end">
      {% for field in comanda_item_form %}
      <div class="col-4 mb-3{% if field.field.required %} {{ form.required_css_class}}{% endif %}">
        {{ field.label_tag }} {% if field.field.required %}*{% endif %}
        <div class="input-group">
          {{ field }}
          {% if field.help_text %}
            <p class="help"> {{ field.help_text|safe }}</p>
          {% endif %}
        </div>
      </div>
      {% endfor %}
      <div class="form-group col-4 mb-3">
        <label></label>
        <button type="submit" class="btn btn-success btn-md"><i class="fas fa-check"></i></button>
        <button type="button" class="btn btn-danger btn-md"
        hx-get="{{ obj.get_edit_url }}"
        hx-target="#receta-{{ obj.id }}"
        hx-swap="outerHTML"
        ><i class="fas fa-cancel"></i></button>
      </div>
    </div>
  </form> 
</td>

templates/apps/comanda/partials/table-form.html
  <div class="table-responsive">
    <div id="error-message">
      {% if msg %}
        {% include 'apps/pedidos/partials/item-deleted.html' %}
      {% endif %}
    </div>
    <table class="table m-0">
      <thead>
        <tr>
          <th></th>
          <th>Cant.</th>
          <th>P.Vol.</th>
          <th>Precio</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td><strong>Totales</strong></td>
          <td>{% if parent_obj.get_cart_count_items %}{{ parent_obj.get_cart_count_items }}{% else %}0{% endif %}</td>
          <td>{% if parent_obj.get_cart_points %}{{ parent_obj.get_cart_points }}{% else %}0{% endif %}</td>
          <td>{% if parent_obj.get_cart_total %}{{ parent_obj.get_cart_total }}{% else %}0{% endif %}</td>
          <td></td>
        </tr>
        {% for obj in parent_obj.get_all_items %}
          {% include 'apps/comanda/partials/comanda-item.html' %}
        {% empty %}
        <tr>
          <td>Sin Datos</td>
          <td>0</td>
          <td>0</td>
          <td>0</td>
          <td></td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
  {% if parent_obj.status == 'p' %}
    <!-- Formulario para Agregar items -->
    <div class="card-body">
      <form hx-post="{{ parent_obj.get_add_receta_url }}" hx-target="#comanda-list-and-form">
        {% csrf_token %}
        <div class="row align-items-end">
          {% for field in comanda_item_form %}
          <div class="col-4 mb-3{% if field.field.required %} {{ comanda_item_form.required_css_class}}{% endif %}">
            {{ field.label_tag }} {% if field.field.required %}*{% endif %}
            <div class="input-group">
              {{ field }}
              {% if field.help_text %}
                <p class="help"> {{ field.help_text|safe }}</p>
              {% endif %}
            </div>
          </div>
          {% endfor %}
        
          <div class="form-group col-4 mb-3">
            <label></label>
            <button id="btn_submit" type="submit" class="btn btn-primary btn-block">Agregar</button>
          </div>
        </div>
      </form>
      
    </div>
  
  {% endif %}
    
  {% include 'apps/comanda/partials/total.html' %}

  {% block js %}

<script>

  document.querySelectorAll('.btn-danger').forEach(button => {
    button.addEventListener('click', function() {
      const url = this.getAttribute('data-url');
      const receta = this.getAttribute('data-receta');
      const cantidad = this.getAttribute('data-cantidad');

      Swal.fire({
          title: 'Confirma',
          text: `¿Quieres eliminar ${receta} x ${cantidad}?`,
          icon: 'warning',
          showCancelButton: true,
          confirmButtonText: 'Sí, eliminar',
          cancelButtonText: 'Cancelar'
      }).then((result) => {
          if (result.isConfirmed) {
              htmx.ajax('DELETE', url, {
                  target: this.getAttribute('hx-target'),
                  swap: 'innerHTML'
              });
          }
      });
    });
    function outputMessage(message, type) {
      Swal.fire({
          title: type === 'error' ? 'Error' : 'Hecho',
          text: message,
          icon: type === 'error' ? 'error' : 'success',
          confirmButtonText: 'Ok'
      });
  }

    function showMessages() {
      {% if messages %}
          {% for message in messages %}
              outputMessage("{{ message.message|escapejs }}", "{{ message.tags }}");
          {% endfor %}
      {% endif %}
  }

    // Mostrar mensajes después de una actualización parcial con HTMX específica
    document.body.addEventListener('htmx:afterRequest', function(event) {
        if (event.detail.elt.getAttribute('data-action') === 'delete') {
            showMessages();
        }
    });

    // Mostrar mensajes al cargar la página
    showMessages();
  });
</script>

{% endblock js %}

templates/apps/comanda/partials/total.html
<!-- Prepagos -->
<div class="card-body" hx-target="this" hx-swap="outerHTML">
  <!-- checkbox -->
  <div class="row">
    <div class="col-5">
      <div class="form-group">
        <label class="col-form-label" ><i class="fas fa-check"></i> Prepagos: </label>
        {% for prepago in parent_obj.get_uniq_prepagos_list %}
          <div class="form-check" >
            <input class="form-check-input" type="checkbox" {% if prepago in parent_obj.get_cart_prepagos %}checked=""{% endif %}
            hx-get="{% url 'comanda:hx-add-prepago' id_comanda=parent_obj.id id_prepago=prepago.id %}" hx-trigger="change" >
            <label class="form-check-label"> {{ prepago }} bs.  <span id="prepagos-usados" class="badge{% if prepago.pagado %} badge-success{% else %} badge-warning{% endif %} ">
                {{ prepago.comanda_set.all.count }}/{{ prepago.cantidad }}
              </span>
            </label>
          </div>
        {% empty %} 
          <div class="form-check">
            <input class="form-check-input" type="checkbox" disabled="">
            <label class="form-check-label">No tiene prepagos </label>
          </div>
        {% endfor %}
      </div>
    </div>
    <div class="col-7">
      <div class="info-box" id="total_a_pagar">
        {% if parent_obj.consumo.transferencia %}
        {% include "apps/comanda/partials/transfer.html" %}
        {% else %}
          {% include "apps/comanda/partials/dollar.html" %}
        {% endif %}

        <div class="info-box-content">
          <span class="info-box-text">Total a pagar</span>
          <div class="custom-control custom-switch">
            <input
              hx-get="{% url 'consumos:crud_transferencia' parent_obj.consumo.id %}"
              hx-trigger="change"
              hx-target="#icon-selected"
              hx-swap="outerHTML"
              type="checkbox" 
              class="custom-control-input" 
              id="qrSwitch"
              name="qrSwitch"
              {% if parent_obj.consumo.transferencia %}
              checked
              {% endif %}
              {% if parent_obj.get_cart_cash == 0 %}
              disabled
              {% endif %}>
            <label class="custom-control-label" for="qrSwitch">{{ parent_obj.get_cart_cash }}</label>
          </div>
        </div>
        <!-- /.info-box-content -->
      </div>
    </div>
  </div>
</div>

<script>


    function outputMessage(message, type) {
      Swal.fire({
          title: type === 'error' ? 'Error' : 'Hecho',
          text: message,
          icon: type === 'error' ? 'error' : 'success',
          confirmButtonText: 'Ok'
      });
    }

    function showMessages() {
      {% if messages %}
          {% for message in messages %}
              outputMessage("{{ message.message|escapejs }}", "{{ message.tags }}");
          {% endfor %}
      {% endif %}
    } 

    // Mostrar mensajes después de una actualización parcial con HTMX específica
    document.body.addEventListener('htmx:afterRequest', function(event) {
        if (event.detail.elt.getAttribute('data-action') === 'delete') {
            showMessages();
        }
    });

    // Mostrar mensajes al cargar la página
    showMessages();

</script>

templates/apps/comanda/partials/transfer.html
<span class="info-box-icon bg-primary" id="icon-selected"><i class="fas fa-money-bill-transfer"></i></span>