bot/urls.py
from django.urls import path
from bot.views import *

app_name = 'bot'

urlpatterns = [
    path('', UpdateBot.as_view(), name='update'),
    path('send/<str:user_id>/', user_send_message, name='send_message'), #type:ignore
    path('send/<str:user_id>/pedido/<str:pedido_id>/', enviar_detalle_pedido, name='send_pedido'), #type:ignore
]

main/urls.py
from django.urls import path
from main.views import *

app_name = 'main'

urlpatterns = [
    path('', inicio_view, name='inicio'),
    path('bot-user-profile/<str:user_id>/', bot_user_profile, name='bot_user_profile'),
    path('bot-user-profile/<str:user_id>/send-message/', bot_user_profile, name='bot_user_message'),
    path('detalle-ahorro/', detalle_ahorro, name='detalle_ahorro'),
    path('search/', search_view, name='search'),
    path('users-list/', users_list_view, name='users_list'),
]

productos/urls.py
from django.urls import path
from productos.views import *
from productos.api import *

app_name = 'productos'

urlpatterns = [
    path('', app_over_view, name='api_products_overview'),
    path('api-list/', products_list, name='api_products_list'),
    path('api-precios-list/', precios_dist_list, name='api_precios_dist_list'),
    path('api-create/', product_create, name='api_product_create'),
    path('api-search/', search_products, name='api_search_products'),
    path('api-detail/<str:pk>/', product_detail, name='api_products_detail'),
    path('api-update-or-create/<str:pk>/', product_update_or_create, name='api_product_update_or_create'),
    path('update/', update_db_view, name='update_bd'),
    path('hx/sabores/', hx_sabores_categoria, name='hx-sabores'),
]

socios/urls.py
from django.urls import path
from socios.views import *

app_name = 'socios'

urlpatterns = [
    path('', socios_list_view, name='list'),
    path('profile/<int:id>', socio_profile_view, name='profile'),
    path('hx/profile/<str:id_socio>', hx_socio_crud, name='hx-profile'),
    path('hx/asistencia/<str:id_socio>', hx_asistencia, name='hx-asistencia'),
    path('hx/referidos/<str:id_socio>', hx_referidos, name='hx-referidos'),
]

main/models.py
from django.db.models import *


class Settings(Model):

    nombre = CharField("Nombre", max_length=50)
    descripcion = CharField(
        "Descripcion", max_length=100, blank=True, null=True)
    valor = CharField("Valor", max_length=50)

    class Meta:
        verbose_name = "Settings"
        verbose_name_plural = "Settings"

    def __str__(self):
        return self.valor

class Monto(Model):

    monto = IntegerField()
    inserted_on = DateField(auto_now_add=True)

    class Meta:
        verbose_name = 'Monto'
        verbose_name_plural = 'Montos'

    def __str__(self):
        return str(self.monto)

main/views.py
import random
from datetime import date
from django.db.models import Sum
from django.shortcuts import render, get_object_or_404
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from productos.models import Categoria, Detalles
from bot.models import BotUser, Activity
from bot.forms import MessageForm
from comanda.models import Comanda
from main.models import Monto
from main.utils import get_today
from socios.models import Socio
from home.decorators import allowed_users


@staff_member_required
def bot_user_profile(request, user_id):
    context, template = {}, 'apps/bot/bot_user_profile.html'
    bot_user = BotUser.objects.get(user_id=user_id)
    form = MessageForm()
    if request.method == 'POST':
        form = MessageForm(request.POST or None)
    context = {
        'user': bot_user,
        'form': form
    }
    return render(request, template, context)

@staff_member_required
def detalle_ahorro(request):
    template = 'apps/main/detalle_ahorro.html'
    amounts_list = Monto.objects.all().order_by('-inserted_on')
    page = request.GET.get('page',  1)
    
    paginator = Paginator(amounts_list, 10)
    try:
        detalle = paginator.page(page)
    except PageNotAnInteger:
        detalle = paginator.page(1)
    except EmptyPage:
        detalle = paginator.page(paginator.num_pages)
    context = {
        'detalle' : detalle 
    }
    return render(request, template, context)


@staff_member_required
def users_list_view(request):
    template = 'apps/bot/users_list.html'
    context = {
        'users_list': BotUser.objects.all().order_by('-inserted_on')
    }

    return render(request, template, context)


@login_required
def inicio_view(request):
    context, template = {}, "apps/main/inicio.html"
    socios = Socio.objects.all()
    productos = Categoria.objects.all()
    detalles = Detalles.objects.all()
    users = BotUser.objects.all()
    # activities = Activity.objects.values('inserted_on__date').distinct().values('user_id').distinct()
    today = get_today()
    activities = Activity.objects.all().order_by('-inserted_on')[:25]
    comandas = Comanda.objects.filter(fecha=today).order_by('-pk')
    try:
        operador = request.user.groups.get(name='operadores')
    except:
        operador = None
    
    context = {
        'productos': productos,
        'detalles' : detalles,
        'users': users,
        'activities': activities,
        'comandas' : comandas,
        'operador' : operador,
        'socios' : socios,
        'latest' : socios.order_by('-persona__created_on')[:8],
        'hoy': today,
    }

    return render(request, template, context)

def get_amount(ok):
    while ok:
        amount = random.randint(1,28)
        ok = False if Monto.objects.filter(monto=amount, inserted_on__icontains=date.today().year).count() <= 13 else True
            
    return amount

# SEARCH_TYPE_MAPPING = {
#     'receta': Receta,
#     'recetas': Receta,
#     'socio': Socio,
#     'socios': Socio
# }

# @staff_member_required
# def search_view(request):
#     context, template = {}, 'apps/main/search/results-view.html'
#     query = request.GET.get('q')
#     search_type = request.GET.get('type')
#     Klass = SEARCH_TYPE_MAPPING[search_type] if search_type in SEARCH_TYPE_MAPPING else Socio
#     qs = Klass.objects.search(query=query)
#     context['objects'] = qs

#     if request.htmx:
#         context['objects'] = qs[:5]
#         template = 'apps/main/search/partials/results.html'
    
#     return render(request, template, context)

# @allowed_users(allowed_roles=['admin', 'operadores'])
def search_view(request):
    context, template = {}, 'apps/main/search/results-view.html'
    query = request.GET.get('q')
    qs = Socio.objects.search(query=query) #type: ignore
    context['objects'] = qs
    if request.htmx:
        context['objects'] = qs[:10]
        template = 'apps/main/search/partials/results.html'
    
    return render(request, template, context)

templates/apps/main/inicio-bak.html
{% extends 'base.html' %}
{% block nombre %}
  Marcelo Llosa
{% endblock nombre %}
{% block page %}Escritorio{% endblock page %}

{% block content-header %}
<!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0 text-dark">Escritorio</h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="{% url 'main:inicio' %}">Inicio</a></li>
              <li class="breadcrumb-item active">Escritorio</li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div><!-- /.content-header -->

{% endblock content-header %}

{% block main-content %}

<div class="row">
  <div class="col-12 col-sm-6 col-md-3">
    <div class="info-box">
      <span class="info-box-icon bg-info elevation-1"><a href="#"><i class="fas fa-cog"></i></a></span>

      <div class="info-box-content">
        <span class="info-box-text">Categorias de Productos</span>
        <span class="info-box-number">
          {{ productos.count }}
        </span>
      </div>
      <!-- /.info-box-content -->
    </div>
    <!-- /.info-box -->
  </div>
  <!-- /.col -->
  
  <!-- fix for small devices only -->
  <div class="clearfix hidden-md-up"></div>

  <div class="col-12 col-sm-6 col-md-3">
    <div class="info-box mb-3">
      <span class="info-box-icon bg-success elevation-1"><i class="fas fa-shopping-cart"></i></span>

      <div class="info-box-content">
        <span class="info-box-text">Sales</span>
        <span class="info-box-number">760</span>
      </div>
      <!-- /.info-box-content -->
    </div>
    <!-- /.info-box -->
  </div>
  <!-- /.col -->
  <div class="col-12 col-sm-6 col-md-3">
    <div class="info-box mb-3">
      <span class="info-box-icon bg-warning elevation-1"><i class="fas fa-users"></i></span>

      <div class="info-box-content">
        <span class="info-box-text">New Members</span>
        <span class="info-box-number">2,000</span>
      </div>
      <!-- /.info-box-content -->
    </div>
    <!-- /.info-box -->
  </div>
  <!-- /.col -->

  <div class="col-12 col-sm-6 col-md-3">
    <div class="info-box mb-3">
      <span class="info-box-icon bg-danger elevation-1"><i class="fas fa-thumbs-up"></i></span>

      <div class="info-box-content">
        <span class="info-box-text">Likes</span>
        <span class="info-box-number">41,410</span>
      </div>
      <!-- /.info-box-content -->
    </div>
    <!-- /.info-box -->
  </div>
  <!-- /.col -->
</div>

<!-- Main content -->
<div class="row">
  <div class="col-lg-3 col-6">
    <!-- small box -->
    <div class="small-box bg-info">
      <div class="inner">
        <h3>{{ productos.count }}</h3>

        <p>Categorias de Productos</p>
      </div>
      <div class="icon">
        <i class="fas fa-bag-shopping"></i>
      </div>
      <a href="#" class="small-box-footer">Ver Detalle <i class="fas fa-arrow-circle-right"></i></a>
    </div>
  </div><!-- ./col -->
  <div class="col-lg-3 col-6">
    <!-- small box -->
    <div class="small-box bg-success">
      <div class="inner">
        <h3>{{ amount }}<sup style="font-size: 20px">Bs</sup></h3>

        <p>Hoy, y el total son <strong>{{ total }} Bs.</strong></p>
      </div>
      <div class="icon">
        <i class="fas fa-chart-bar"></i>
      
      </div>
      <a href="{% url 'main:detalle_ahorro' %}" class="small-box-footer">Ver Detalle <i class="fas fa-arrow-circle-right"></i></a>
    </div>
  </div><!-- ./col -->
  <div class="col-lg-3 col-6">
    <!-- small box -->
    <div class="small-box bg-warning">
      <div class="inner">
        <h3>{{ users.count }}</h3>

        <p>Bot User Registrations</p>
      </div>
      <div class="icon">
        <i class="ion ion-person-add"></i>
      </div>
      <a href="{% url 'main:users_list' %}" class="small-box-footer">Ver Detalle <i class="fas fa-arrow-circle-right"></i></a>
    </div>
  </div><!-- ./col -->
  <div class="col-lg-3 col-6">
    <!-- small box -->
    <div class="small-box bg-danger">
      <div class="inner">
        <h3>65</h3>

        <p>Unique Visitors</p>
      </div>
      <div class="icon">
        <i class="ion ion-pie-graph"></i>
      </div>
      <a href="#" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
    </div>
  </div><!-- ./col -->
</div><!-- /.row -->
<div class="row">
  <div class="col-lg-6"></div>
  <div class="col-lg-6">
    <!-- TO DO list -->
    <div class="card" style="position: relative; left: 0px; top: 0px;">
      <div class="card-header ui-sortable-handle" style="cursor: move;">
        <h3 class="card-title">
          <i class="ion ion-clipboard mr-1"></i>
          To Do List
        </h3>

        <div class="card-tools">
          <ul class="pagination pagination-sm">
            <li class="page-item"><a href="#" class="page-link">«</a></li>
            <li class="page-item"><a href="#" class="page-link">1</a></li>
            <li class="page-item"><a href="#" class="page-link">2</a></li>
            <li class="page-item"><a href="#" class="page-link">3</a></li>
            <li class="page-item"><a href="#" class="page-link">»</a></li>
          </ul>
        </div>
      </div>
      <!-- /.card-header -->
      <div class="card-body">
        <ul id="list-wrapper" class="todo-list ui-sortable" data-widget="todo-list">
          
          
          <li class="">
            <!-- drag handle -->
            <span class="handle ui-sortable-handle">
              <i class="fas fa-ellipsis-v"></i>
              <i class="fas fa-ellipsis-v"></i>
            </span>
            <!-- checkbox -->
            <div class="icheck-primary d-inline ml-2">
              <input type="checkbox" value="" name="todo1" id="todoCheck1">
              <label for="todoCheck1"></label>
            </div>
            <!-- todo text -->
            <span class="text">Design a nice theme</span>
            <!-- Emphasis label -->
            <small class="badge badge-danger"><i class="far fa-clock"></i> 2 mins</small>
            <!-- General tools such as edit or delete-->
            <div class="tools">
              <i class="fas fa-edit"></i>
              <i class="fas fa-trash"></i>
            </div>
          </li>
          <li class="">
            <span class="handle ui-sortable-handle">
              <i class="fas fa-ellipsis-v"></i>
              <i class="fas fa-ellipsis-v"></i>
            </span>
            <div class="icheck-primary d-inline ml-2">
              <input type="checkbox" value="" name="todo3" id="todoCheck3">
              <label for="todoCheck3"></label>
            </div>
            <span class="text">Let theme shine like a star</span>
            <small class="badge badge-warning"><i class="far fa-clock"></i> 1 day</small>
            <div class="tools">
              <i class="fas fa-edit"></i>
              <i class="fas fa-trash"></i>
            </div>
          </li>
          <li class="">
            <span class="handle ui-sortable-handle">
              <i class="fas fa-ellipsis-v"></i>
              <i class="fas fa-ellipsis-v"></i>
            </span>
            <div class="icheck-primary d-inline ml-2">
              <input type="checkbox" value="" name="todo4" id="todoCheck4">
              <label for="todoCheck4"></label>
            </div>
            <span class="text">Let theme shine like a star</span>
            <small class="badge badge-success"><i class="far fa-clock"></i> 3 days</small>
            <div class="tools">
              <i class="fas fa-edit"></i>
              <i class="fas fa-trash"></i>
            </div>
          </li>
          <li class="">
            <span class="handle ui-sortable-handle">
              <i class="fas fa-ellipsis-v"></i>
              <i class="fas fa-ellipsis-v"></i>
            </span>
            <div class="icheck-primary d-inline ml-2">
              <input type="checkbox" value="" name="todo5" id="todoCheck5">
              <label for="todoCheck5"></label>
            </div>
            <span class="text">Check your messages and notifications</span>
            <small class="badge badge-primary"><i class="far fa-clock"></i> 1 week</small>
            <div class="tools">
              <i class="fas fa-edit"></i>
              <i class="fas fa-trash"></i>
            </div>
          </li>
          <li class="">
            <span class="handle ui-sortable-handle">
              <i class="fas fa-ellipsis-v"></i>
              <i class="fas fa-ellipsis-v"></i>
            </span>
            <div class="icheck-primary d-inline ml-2">
              <input type="checkbox" value="" name="todo6" id="todoCheck6">
              <label for="todoCheck6"></label>
            </div>
            <span class="text">Let theme shine like a star</span>
            <small class="badge badge-secondary"><i class="far fa-clock"></i> 1 month</small>
            <div class="tools">
              <i class="fas fa-edit"></i>
              <i class="fas fa-trash"></i>
            </div>
          </li>
        </ul>
      </div>
      <!-- /.card-body -->
      <div class="card-footer clearfix">
        <form id="form-wrapper" action="#" method="post">
          <div class="input-group">
            <input type="text" name="message" placeholder="Type Message ..." class="form-control">
            <span class="input-group-append">
              <button type="submit" class="btn btn-info float-right"><i class="fas fa-plus"></i> Add item</button>
              <!-- <button type="button" class="btn btn-primary">Send</button> -->
            </span>
          </div>
        </form>
        
      </div>
    </div>
  </div><!-- /.col-md-6 -->
</div><!-- /.row -->
<div class="row">
  <div class="col-md-12">
    <!-- The time line -->
    <div class="timeline">
      <!-- timeline time label -->
      <div class="time-label">
        <span class="bg-red">10 Feb. 2014</span>
      </div><!-- /.timeline-label -->
      {% for activity in activities %}
      <!-- timeline item -->
      <div>
        <i class="fas fa-user bg-green"></i>
        <div class="timeline-item">
          <span class="time"><i class="fas fa-clock"></i> hace {{ activity.inserted_on|timesince }}</span>
          <h3 class="timeline-header">
            <a href="{% url 'main:bot_user_profile' user_id=activity.user.user_id %}">
              {{ activity.user.first_name }} 
              {% if activity.user.last_name %}{{ activity.user.last_name }}{% endif %}
              {% if activity.user.username %}({{ activity.user.username }}){% endif %}
            </a> escribió: </h3>

          <div class="timeline-body">
            {{ activity.text }}
          </div>
          <div class="timeline-footer">
            <a class="btn btn-primary btn-sm">Read more</a>
            <a class="btn btn-danger btn-sm">Delete</a>
          </div>
        </div>
      </div>
      <!-- END timeline item -->
        {% comment %} <i class="fas fa-user bg-green"></i>
        <div class="timeline-item">
          <span class="time"><i class="fas fa-clock"></i>hace {{ activity.inserted_on|timesince }}</span>
          <h3 class="timeline-header no-border"><a href="{% url 'main:bot_user_profile' user_id=activity.user.user_id %}">{{ activity.user.first_name }} 
          {% if activity.user.last_name %}{{ activity.user.last_name }}{% endif %}
          {% if activity.user.username %}({{ activity.user.username }}){% endif %}
          </a> escribio "{{ activity.text }}"</h3>
        </div> {% endcomment %}
      {% empty %}{% endfor %}

    </div><!-- /.timeline -->
  </div><!-- /.col -->
</div><!-- /.row -->
{% endblock main-content %}

{% block js %}

<script>
  buildList()

  function buildList(){
  var wrapper = document.getElementById('list-wrapper')
  var url = "{% url 'productos:api_products_list' %}"
  fetch(url)
  .then((resp) => resp.json())
  .then(function(data){
    console.log('Data:', data)
    var list = data
    for (var i in list){
      var item = `
        <li>
          <span class="handle ui-sortable-handle">
            <i class="fas fa-ellipsis-v"></i>
            <i class="fas fa-ellipsis-v"></i>
          </span>
          <div class="icheck-primary d-inline ml-2">
            <input type="checkbox" value="" name="todo${i}" id="todoCheck${i}">
            <label for="todoCheck${i}"></label>
          </div>
          <span class="text">${list[i].nombre}</span>
          <small class="badge badge-info"><i class="far fa-clock"></i> ${list[i].edited_on} </small>
          <div class="tools">
            <i class="fas fa-edit"></i>
            <i class="fas fa-trash"></i>
          </div>
        </li>
      `
      wrapper.innerHTML += item
    }
  })
}

  var form = document.getElementById('form-wrapper')
  form.addEventListener('submit', function(e){
    e.preventDefault()
    console.log('Form Submitted')
    var url = ''
  })


</script>


{% endblock js %}

templates/apps/main/inicio.html
{% extends 'base.html' %}
{% load static %}

{% block nombre %}
  Marcelo Llosa
{% endblock nombre %}
{% block page %}Escritorio{% endblock page %}

{% block content-header %}
<!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0 text-dark">Escritorio</h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item active">Inicio</li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div><!-- /.content-header -->

{% endblock content-header %}

{% block main-content %}

<div class="row">
  <div class="col-lg-8">
    <div class="card" id="cardConsumos" hx-target="this" hx-swap='outerHTML'>
      <div class="card-header border-transparent">
        <h3 class="card-title">{{ hoy | date:'d M Y' }}</h3>

        <div class="card-tools">
          <span class="badge badge-info"> Consumos: {{ comandas.count }}</span>
          <button type="button" class="btn btn-tool" data-card-widget="collapse">
            <i class="fas fa-minus"></i>
          </button>
          <button type="button" class="btn btn-tool" 
            hx-get="{% url 'main:inicio' %}" 
            hx-select="#cardConsumos"
            hx-trigger="click"
            _="on htmx:beforeRequest put 'flex' into #loadingOverlay.style.display
              on htmx:afterRequest put 'none' into #loadingOverlay.style.display"
            >
            <i class="fas fa-sync-alt"></i>
          </button>
        </div>
      </div>
      <!-- /.card-header -->
      <div class="card-body p-0">
        <div class="table-responsive" id="consumosDiarios">
          <table class="table m-0" id="tablaConsumos">
            <thead>
            <tr>
              <th>Nombre</th>
              <th>Estado</th>
              <th>Total</th>
              <th>Detalle</th>
            </tr>
            </thead>
            <tbody>
            {% for comanda in comandas %}
            <tr>
              <td><a href={{ comanda.socio.get_absolute_url }}>{{ comanda.socio }}</a></td>
              {% include "apps/main/partials/status.html" %}
              <td>{{ comanda.get_cart_total }}</td>
              <td>
                  <div class="sparkbar" data-color="#f39c12" data-height="20">
                  {% for item in comanda.get_all_items %}  
                      {% if forloop.last %}
                      {{item}}
                      {% else %}
                      {{item}},
                      {% endif %}
                  {% endfor %}
                  </div>
              </td>
            </tr>
            {% empty %}
            <tr>
              <td colspan="2">No hay Ordenes</td>
            </tr>
            {% endfor %}
            </tbody>
          </table>
        </div>
        <!-- /.table-responsive -->
      </div>
      <!-- Overlay to show when loading -->
      <div class="overlay" id="loadingOverlay" style="display: none;">
        <i class="fas fa-2x fa-sync-alt fa-spin"></i>
      </div>
      <!-- /.card-body -->
    </div>
  </div>
  <div class="col-lg-4">
    <div class="card">
        <div class="card-header">
          <h3 class="card-title">Registros Recientes</h3>

          <div class="card-tools">
            <span class="badge badge-danger">8 Recientes</span>
            <button type="button" class="btn btn-tool" data-card-widget="collapse">
              <i class="fas fa-minus"></i>
            </button>
            <button type="button" class="btn btn-tool" data-card-widget="remove">
              <i class="fas fa-times"></i>
            </button>
          </div>
        </div>
        <!-- /.card-header -->
        <div class="card-body p-0">
          <ul class="users-list clearfix">
            {% for socio in latest %}
            <li>
              <img src="{{ socio.persona.get_profile_pic_url }}" alt="User Image">
              <a class="users-list-name" href="{{ socio.get_absolute_url }}">{{ socio.persona.nombre }} {{ socio.persona.apellido }}</a>
              <span class="users-list-date">{{ socio.persona.created_on }}</span>
            </li>
            {% endfor %}
            
          </ul>
          <!-- /.users-list -->
        </div>
        <!-- /.card-body -->
        <div class="card-footer text-center">
          <a href=" {% url 'socios:list' %}">Todos los Socios</a>
        </div>
        <!-- /.card-footer -->
      </div>
  </div>
</div>
{% endblock main-content %}
{% block js %}
<script>
  function outputMessage(error){
    Swal.fire({
      icon: 'warning',
      title: error,
      text: 'Something went wrong!',
      footer: '<a href="{% url "main:inicio" %}" >Why do I have this issue?</a>'
    })
  }
</script>
{% endblock js %}